### ISSUE TITLE
TabularDataset extension

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/privacy-sdg-toolbox#17]
Some implementations proposed by @JamesJordon on the TabularDatasetClass still remaining.

- Add `inplace` option for the add, drop, replace methods. See [comment](https://github.com/alan-turing-institute/privacy-sdg-toolbox/pull/11#discussion_r849660495).

- Add option to declare a column as an index (in case we want to index by an identifier, etc). See comment in [here](https://github.com/alan-turing-institute/privacy-sdg-toolbox/pull/11#discussion_r849658922).

- Decide if we are defining more than one target record as a TabularDataset or a list of 1 row Tabular datasets. See comment [here](https://github.com/alan-turing-institute/privacy-sdg-toolbox/pull/11#discussion_r849658922).

- Use types from data description on reading the dataframe (once we have settled on a format).

**Comment by JamesJordon** [comment]
I think we should consider whether or not we want to create a separate `Record` class. Whatever object `target_record` ends up being, it would be nice to call, for example, `target_record.id` to get its ID.

**Comment by JamesJordon** [comment]
I would like a `.empty()` method on `TabularDataset` that returns an empty (0 rows) version of the dataset.

**Comment by JamesJordon** [comment]
Closing, outstanding features are now in #28 and #30
