### ISSUE TITLE
Implement dataset class

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/privacy-sdg-toolbox#3]
Initial idea from meeting on 7th April:

![78ab4b22-b525-4376-bfa1-bc5af29d8efa](https://user-images.githubusercontent.com/11162074/162163650-9b3cd03c-a6b4-4819-bb2e-2a596b30dcda.jpeg)

**Comment by crangelsmith** [comment]
Something we need to coordinate with @callummole is how DD1 will look like. The [QUiPP style](https://github.com/alan-turing-institute/QUIPP-pipeline/blob/develop/datasets/polish_data_2011/polish_data_2011.json) is slightly different to the [Stadler](https://github.com/alan-turing-institute/privacy-sdg-toolbox/blob/api/data/texas.json).

**Comment by triangle-man** [comment]
Requires #4

**Comment by crangelsmith** [comment]
- Use a class method for instatiation on the TabularDataset
