### ISSUE TITLE
Define the format of datasets

### ISSUE THREAD

**Issue by triangle-man** [alan-turing-institute/privacy-sdg-toolbox#4]
A format specification is required so that our toolbox can 
- read the "raw" data provided by the user
- generate inputs to the user-provided privacy-enhancing code
- read the outputs from the user's privacy-enhancing code

Required by #3

**Comment by crangelsmith** [comment]
Do we have an example that we like that we can use for the early development of the toolbox? We could start with a very minimal version of a test dataset and discover along the way we want to add more complexity to the schema. 

I'm thinking particularly for writing the first tests. For the Dataset class, I would like to know the columns to be read from the CSV file and the types of those columns.

**Comment by JamesJordon** [comment]
I don't have a strong preference. I think that ideally the schema will be minimal, but that we will load it into a `DataDescription` class that will have all the bells and whistles we would need? In that sense, the schema will ideally only implement "redundant" information for the purposes of self-checking (but this might also get in the way and we should just avoid redundancy?).

**Comment by crangelsmith** [comment]
@JamesJordon I was thinking that the data description could live in the Dataset class, it feels too intricated with the data to be independent, but i can be convinced otherwise?

**Comment by JamesJordon** [comment]
I definitely think the data description should be an attribute of `dataset`. But my thinking is that we define a separate class, `DatasetDescription`, for handling and housing the data description, and then `dataset.description` is an instance of `DatasetDescription`, so that all methods related to manipulating/loading (and maybe even automatic generation) of descriptions are housed there, to keep the `Dataset` cleaner.

**Comment by crangelsmith** [comment]
@triangle-man to make a JSON schema to create a JSON file. Also is going to make an example for the [texas dataset](https://github.com/alan-turing-institute/privacy-sdg-toolbox/blob/main/privE/tests/data/texas.csv) for development.

**Comment by triangle-man** [comment]
Added "enhancement" label because I also need to fix the TabularDatasets class to be able to read the new format.

**Comment by callummole** [comment]
Dataset format in progress [here](https://github.com/alan-turing-institute/privacy-sdg-toolbox/tree/dataset-schema/prive/datasets)

**Comment by triangle-man** [comment]
Summary of format reproduced below:

| `type`                    | `representation`    | Meaning                               |
|---------------------------|---------------------|---------------------------------------|
| `finite`                  | An integer, N       | 0, 1, 2, ..., N - 1                   |
|                           | An array of strings | The given strings                     |
|                           |                     |                                       |
| `finite/ordered`          | An integer, N       | 0, 1, 2, ..., N - 1                   |
|                           | An array of strings | The given strings, in the given order |
|                           |                     |                                       |
| `countable`               | `"integer"`         | 0, 1, 2, ...,                         |
|                           | `"string"`          | Any string                            |
|                           |                     |                                       |
| `countable/ordered`       | `"integer"`         | ..., -2, -1, 0, 1, 2, ...             |
|                           | `"date"`            | YYYY-MM-DD or YYYYMMDD                |
|                           |                     |                                       |
| `countable/ordered/least` | `"integer"`         | 0, 1, 2, ...                          |
|                           | `"string"`          | Strings, with dictionary order        |
|                           |                     |                                       |
| `real`                    | `"number"`          | Any decimal approximation             |
|                           | `"datetime"`        | YYYY-MM-DDThh:mm:ss.sss, or           |
|                           |                     | YYYYMNMDDThhmmss.sss                  |
|                           |                     |                                       |
| `real/non-negative`       | `"number"`          | Any decimal approximation             |
|                           |                     |                                       |
| `interval`                | `"number"`          | The closed interveal [0, 1].          |

**Comment by triangle-man** [comment]
Notes from today's meeting:

- For now, we do *not* support "missing" as a value for any type other than those represented as strings; and there it has no special meaning.

**Comment by callummole** [comment]
see #23 for example
